In [2]:
%matplotlib inline

In [3]:
from src.utils.load_processed_data import load_iris
from src.naive_bayes import (NaiveBayes, 
                             GaussianNaiveBayes, 
                             MixedNaiveBayes)
from src.evaluators import MetricsEvaluator
from src.digitisers import (MultipleAttributeTransformer,
                            RoundDigitizer, KMeansDigitizer,
                            DiscreteEncoder)
from src.cross_validation import CrossValidator

In [4]:
import pandas as pd
import numpy as np
import seaborn as sbn
from matplotlib import pyplot as plt

# Iris

In [5]:
X, Y = load_iris()

In [80]:
transformers = {i: DiscreteEncoder() for i in range(X.shape[1])}
transformer = lambda: MultipleAttributeTransformer(transformers)

In [84]:
cv = CrossValidator(X, Y, lambda: NaiveBayes(True), transformer)

In [132]:
mevs = cv.kfold_cross_validation(10, shuffle=True)

df = pd.DataFrame()#{"Value": [0,0,0,0]}, 
                  #index=['Accuracy','Precision','Recall','F Measure'])

df.loc['Accuracy','Value'] = np.asarray([m.accuracy() for m in mevs])[0]#.mean()
df.loc['Precision','Value'] = np.asarray([m.precision() for m in mevs])[0]#.mean()
df.loc['Recall','Value'] = np.asarray([m.recall() for m in mevs])[0]#.mean()
df.loc['F Measure','Value'] = np.asarray([m.f_measure() for m in mevs])[0]#.mean()
df
#print(np.asarray([m.confusion_matrix() for m in mevs]))

Value
Accuracy   0.933333
Precision  0.933333
Recall     0.933333
F Measure  0.933333

In [73]:
mevs = cv.stratified_kfold_cross_validation(10, True)

print(np.asarray([m.accuracy() for m in mevs]).mean())
print(np.asarray([m.f_measure() for m in mevs]).mean())
print(np.asarray([m.precision() for m in mevs]).mean())
print(np.asarray([m.recall() for m in mevs]).mean())
print(np.asarray([m.confusion_matrix() for m in mevs]))

0.913333333333
0.913333333333
0.913333333333
0.913333333333
[[[5 0 0]
  [0 4 1]
  [0 0 5]]

 [[5 0 0]
  [0 5 0]
  [0 1 4]]

 [[5 0 0]
  [0 5 0]
  [0 2 3]]

 [[5 0 0]
  [0 4 1]
  [0 0 5]]

 [[5 0 0]
  [0 4 1]
  [0 0 5]]

 [[5 0 0]
  [0 2 3]
  [0 0 5]]

 [[5 0 0]
  [0 5 0]
  [0 1 4]]

 [[5 0 0]
  [0 5 0]
  [0 0 5]]

 [[5 0 0]
  [0 4 1]
  [0 0 5]]

 [[5 0 0]
  [1 4 0]
  [0 1 4]]]
